version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Build phase started"
      - npm run start

artifacts:
  files:
    - "**/*"
