version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install -g serve
  build:
    commands:
      - echo Build started on `date`
      - echo Compressing files...
      - tar -czf webapp.tar.gz index.html
artifacts:
  files:
    - webapp.tar.gz
